aux_links:
  'Aweseome Digital History on GitHub':
    - '//github.com/maehr/awesome-digital-history'
description: A curated list of awesome things related to digital history.
gh_edit_branch: 'main' # the branch that your docs is served from
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: 'Edit this page on GitHub.'
gh_edit_repository: 'https://github.com/maehr/awesome-digital-history' # the github URL for your repo
gh_edit_view_mode: 'tree' # "tree" or "edit" if you want the user to jump into the editor immediately
last_edit_time_format: '%b %e %Y at %I:%M %p' # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
remote_theme: just-the-docs/just-the-docs
show_downloads: false
theme: 'just-the-docs'
title: Awesome Digital History
